// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/module/interfaces/module-client.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	entity "github.com/SmokingElk/MWS-2025-Autumn-Intership/internal/domain/module/entity"
	entity0 "github.com/SmokingElk/MWS-2025-Autumn-Intership/internal/domain/version/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockModuleClient is a mock of ModuleClient interface.
type MockModuleClient struct {
	ctrl     *gomock.Controller
	recorder *MockModuleClientMockRecorder
}

// MockModuleClientMockRecorder is the mock recorder for MockModuleClient.
type MockModuleClientMockRecorder struct {
	mock *MockModuleClient
}

// NewMockModuleClient creates a new mock instance.
func NewMockModuleClient(ctrl *gomock.Controller) *MockModuleClient {
	mock := &MockModuleClient{ctrl: ctrl}
	mock.recorder = &MockModuleClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModuleClient) EXPECT() *MockModuleClientMockRecorder {
	return m.recorder
}

// GetLastVersion mocks base method.
func (m *MockModuleClient) GetLastVersion(ctx context.Context, module entity.Module) (entity0.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastVersion", ctx, module)
	ret0, _ := ret[0].(entity0.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastVersion indicates an expected call of GetLastVersion.
func (mr *MockModuleClientMockRecorder) GetLastVersion(ctx, module interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastVersion", reflect.TypeOf((*MockModuleClient)(nil).GetLastVersion), ctx, module)
}
