// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repo/interfaces/repo-hub-client.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	entity "github.com/SmokingElk/MWS-2025-Autumn-Intership/internal/domain/repo/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockRepoHubClient is a mock of RepoHubClient interface.
type MockRepoHubClient struct {
	ctrl     *gomock.Controller
	recorder *MockRepoHubClientMockRecorder
}

// MockRepoHubClientMockRecorder is the mock recorder for MockRepoHubClient.
type MockRepoHubClientMockRecorder struct {
	mock *MockRepoHubClient
}

// NewMockRepoHubClient creates a new mock instance.
func NewMockRepoHubClient(ctrl *gomock.Controller) *MockRepoHubClient {
	mock := &MockRepoHubClient{ctrl: ctrl}
	mock.recorder = &MockRepoHubClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoHubClient) EXPECT() *MockRepoHubClientMockRecorder {
	return m.recorder
}

// GetRepo mocks base method.
func (m *MockRepoHubClient) GetRepo(ctx context.Context, url string, builder func([]byte) (entity.Repo, error)) (entity.Repo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepo", ctx, url, builder)
	ret0, _ := ret[0].(entity.Repo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepo indicates an expected call of GetRepo.
func (mr *MockRepoHubClientMockRecorder) GetRepo(ctx, url, builder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepo", reflect.TypeOf((*MockRepoHubClient)(nil).GetRepo), ctx, url, builder)
}
